# docs: https://rust-lang.github.io/mdBook
[book]
title = "d2mcpp | D2X - Modern C++ Core Language Features"
author = "sunrispeak"
language = "en"

[build]
build-dir = "../book/en"

[output.html]
git-repository-url = "https://github.com/mcpp-community/d2mcpp"

[preprocessor.foo]
# Add any additional configurations
