# docs: https://rust-lang.github.io/mdBook
[book]
title = "d2mcpp | 动手学现代C++核心语言特性"
author = "sunrispeak"
language = "zh"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/mcpp-community/d2mcpp"

[preprocessor.foo]
# Add any additional configurations
